### ISSUE TITLE
Configure or drop CodeClimate

### ISSUE THREAD

**Issue by franzliedke** [openHPI/hpi-connect-portal#574]
If you want to keep CodeClimate, it needs to be re-configured for this repo after the repo move.

What needs to be done:
- [ ] Connect CodeClimate to this repo
- [ ] Make sure it still works after the recent update (#572) - as far as I can tell, it might need an additional step in our Travis build script now

If you don't want / need it, feel free to drop all remains (references in Travis config, gems and spec setup).

**Comment by caustt** [comment]
We decided to drop it, I deleted the gems, and as far as I can tell, there weren't any references in travis.yml or anywhere else.

**Comment by franzliedke** [comment]
Thanks.
